x0 = [1.5, 0.6];

lb = [0.3, 0.2];
ub = [5.0, 5.0];

opts = optimoptions('fmincon', ...
    'Algorithm','sqp', ...
    'Display','iter', ...
    'MaxFunctionEvaluations',40);

[x_opt, t_opt] = fmincon( ...
    @objective_dicurrent, ...
    x0, [], [], [], [], ...
    lb, ub, ...
    @constraints_dicurrent, ...
    opts);

fprintf('Optimal I1 = %.3f A\n', x_opt(1));
fprintf('Optimal I2 = %.3f A\n', x_opt(2));
fprintf('Charging time = %.1f s\n', t_opt);
